Fix nexstep radio issue
baltimorecounty/react-questionnaire--old pull request #5
Opened 2018-01-12 15:00 UTC by martypowell

- Includes a fix for some bad logic, see #4 
- Updates to the readme and a step by step guide to create a questionnaire

2018-01-16 14:09 UTC, mxsnyder submitted a review, later dismissed

2018-01-16 14:21 UTC, martypowell commented
@mxsnyder sorry, one more review, the app was building properly, and failed to move it to it's own branch.

2018-02-28 21:35 UTC, ascire requested changes
Wasn't expecting to play the role of Editor, but here we are.

2018-02-28 21:35 UTC, ascire commented on creating-a-new-questionnaire.md
> +In this example, we will build a questionnaire that will evaluate this guide. (I know very meta ,right?)
> I know very meta ,right?

Fix spacing around comma.

2018-02-28 21:35 UTC, ascire commented on creating-a-new-questionnaire.md
> +- Ask the user if they had any problems creating this sample questionnaire. Possible answers are "Yes" and "No"
Since it's requirements I'd say use numbering instead of bullets, but here I'm just picking nits.

2018-02-28 21:35 UTC, ascire commented on creating-a-new-questionnaire.md
> +In this step we simply want to thank the user for taking the questionnaire and end it. If we look options for question 1, we see that the next step has an id of 3. That id, doesn't exist, so lets cre
> That id, doesn't exist

Remove comma.

2018-02-28 21:35 UTC, ascire commented on creating-a-new-questionnaire.md
> +Make sure the questions work as you setup, if not modify them as needed.
Rewrite:

> Make sure the questions work as you setup. If not, modify them as needed.

2018-02-28 21:35 UTC, ascire commented on src/questionnaires/online-reporting-lostproperty.questionnaire.js
> +		fieldType: "radio",
Fix indentation?

2018-02-28 21:35 UTC, ascire commented on src/questionnaires/online-reporting-lostproperty.questionnaire.js
> +		key: "hasSerialNumber",
Fix indentation.

2018-02-28 21:35 UTC, ascire commented on src/questionnaires/online-reporting-lostproperty.questionnaire.js
> +		key: "valueGreaterThan15000",
More indentation

2018-03-01 14:07 UTC, ascire submitted a review, later dismissed

2018-03-01 14:15 UTC, martypowell commented
@ascire ready for another look

2018-03-08 15:32 UTC, ascire approved these changes

2018-03-08 18:43 UTC, merged